version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install node dependencies
          command: npm install
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install Jest
          command: npm install -g jest
      - run:
          name: Run Tests
          command: npm jest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
