version: 2
jobs:
  Tests:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install node dependencies
          command: npm install
    steps:
      - run:
          name: Run Tests
          command: npm test