export const REQUEST_VIDEO = 'REQUEST_VIDEO';
export const RECEIVE_VIDEO = 'RECEIVE_VIDEO';
export const RECEIVE_VIDEO_FAILURE = 'RECEIVE_VIDEO_FAILURE';

export const REQUEST_QUIZ = 'REQUEST_QUIZ';
export const RECEIVE_QUIZ = 'RECEIVE_QUIZ';
export const RECEIVE_QUIZ_FAILURE = 'RECEIVE_QUIZ_FAILURE';
